from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_view, name='profile'),
    path('donors/', views.donors_view, name='donors'),
    path('save-contact/', views.save_contact),
    path('delete-contact/<int:id>/', views.delete_contact),
    path('get-contacts/', views.get_contacts),
    path('save-call/', views.save_call_history),
    path('get-calls/', views.get_call_history),
    path('firstaid/', views.firstaid_view, name='firstaid'),
    path('firstaid/<int:id>/', views.firstaid_detail),
    path('update-profile/', views.update_profile, name='update_profile'),
    path("send-otp/", views.send_otp),
    path("verify-otp/", views.verify_otp),
    path("donor-register/", views.donor_register, name="donor_register"),
    path("forgot-password/", views.forgot_password, name="forgot_password"),
    path("verify-reset-otp/", views.verify_reset_otp, name="verify_reset_otp"),
    path("reset-password/", views.reset_password, name="reset_password"),
    path("check-username/", views.check_username, name="check_username"),
    path("save-live-location/", views.save_live_location, name="save_live_location"),
    path("trigger-emergency/", views.trigger_emergency, name="trigger_emergency"),
    path("get-nearby-alerts/", views.get_nearby_alerts, name="get_nearby_alerts"),
    path("accept-rescue/", views.accept_rescue),
    path("deny-rescue/", views.deny_rescue),
    path("live-tracking/", views.live_tracking, name="live_tracking"),
    path("get-live-locations/", views.get_live_locations),
    path("stop-emergency/", views.stop_emergency),
    path("close-emergency/", views.close_emergency),
    path("leave-rescue/", views.leave_rescue, name="leave_rescue"),
    path("check-helping-status/", views.check_helping_status),
    path("check-my-emergency/", views.check_my_emergency),
    path("get-active-helpers/", views.get_active_helpers),
    path("check-alert-status/", views.check_alert_status, name="check_alert_status"),
    path("get-active-rescue/", views.get_active_rescue),
    path("update-location/",views.update_location),
    ]