# Generated by Django 5.2.5 on 2026-01-22 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_donor_address_remove_donor_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstAidTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Emoji or icon class', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FirstAidStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='accounts.firstaidtopic')),
            ],
        ),
    ]
