# Generated by Django 5.2.5 on 2026-01-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_firstaidtopic_firstaidstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstaidtopic',
            name='icon',
            field=models.CharField(max_length=10),
        ),
    ]
