# Generated by Django 5.2.5 on 2026-01-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_firstaidtopic_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstaidtopic',
            name='icon',
        ),
    ]
