# Generated by Django 5.2.5 on 2026-01-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_firstaidtopic_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstaidtopic',
            name='category',
            field=models.CharField(default='General', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstaidtopic',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='General', max_length=10),
            preserve_default=False,
        ),
    ]
