# Generated by Django 5.2.5 on 2026-01-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_firstaidtopic_category_firstaidtopic_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycallhistory',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencycallhistory',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
