# Generated by Django 5.2.5 on 2026-01-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_userprofile_email_otp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodGroup',
        ),
    ]
