# Generated by Django 6.0.1 on 2026-02-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_emergencyalert_rescuer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyalert',
            name='rescuer',
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='accepted_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='max_rescuers',
            field=models.IntegerField(default=5),
        ),
    ]
