# Generated by Django 6.0.1 on 2026-02-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_rescue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescue',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
