# Generated by Django 6.0.1 on 2026-02-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_rescue_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyalert',
            name='accepted_count',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='max_rescuers',
        ),
    ]
