# Generated by Django 6.0.1 on 2026-02-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_emergencyalert_victim'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescue',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rescue',
            name='victim_closed',
            field=models.BooleanField(default=False),
        ),
    ]
