# Generated by Django 6.0.1 on 2026-03-04 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alertnotification_emergencylog_helperrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helperrating',
            name='helper',
        ),
        migrations.RemoveField(
            model_name='helperrating',
            name='rescue',
        ),
        migrations.RemoveField(
            model_name='helperrating',
            name='victim',
        ),
        migrations.RenameField(
            model_name='emergencylog',
            old_name='helpers_count',
            new_name='helpers_joined',
        ),
        migrations.RenameField(
            model_name='rescue',
            old_name='closed_at',
            new_name='completed_at',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='rescue',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emergencylog',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rescue',
            name='joined_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rescue',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], max_length=20),
        ),
        migrations.DeleteModel(
            name='AlertNotification',
        ),
        migrations.DeleteModel(
            name='HelperRating',
        ),
    ]
