# Generated by Django 6.0.1 on 2026-03-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_helperrating_helper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rescue_count',
            field=models.IntegerField(default=0),
        ),
    ]
