# Generated by Django 6.0.1 on 2026-03-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_userprofile_rescue_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vehicle',
            field=models.CharField(default='bike', max_length=10),
        ),
    ]
